# Generated by Django 4.2.5 on 2023-12-04 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0183_protect_child_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='starting_unit',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
